---
- name: Check uptime
  ansible_python_interpreter: auto_legacy_silent
  hosts: all
  tasks:
    - name: Execute the Uptime command over Command module
      register: uptimeoutput
      command: uptime
    - debug:
        var: uptimeoutput.stdout_lines
