---
- name: Check uptime
  hosts: all
  tasks:
    - name: Execute the Uptime command over Command module
      register: uptimeoutput
      command: uptime
        vars:
          ansible_python_interpreter: auto_legacy


    - debug:
        var: uptimeoutput.stdout_lines
