---
- name: Check uptime
  hosts: all
  tasks:
    - name: Execute the Uptime command over Command module
      register: uptimeoutput
        vars:
          ansible_python_interpreter: auto_legacy_silent
      command: uptime

    - debug:
        var: uptimeoutput.stdout_lines
