---
- name: Ansible apt module examples
  hosts: all
  become: yes
  tasks:
    - name: Ansible apt to install multiple packages - LAMP
      register: updatesys
      apt:
        update_cache: yes
        name:
          - firewalld
          - apache2
          - mariadb-server
          - php
          - php-mysql
        state: present