---
- name: Report OS release
  hosts: all
  become: true
  tasks:
    - shell: cat /proc/version
      register: shell_result

    - debug:
        var: shell_result.stdout_lines

#lsb_release -a
#uname -a
#cat /proc/version
