---
- hosts: all
  ansible_user: secengadmin
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.buitin.debug:
        msg: "priviledge escalation success"
    - name: Update and upgrade apt packages
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 86400 # 1 day
