---
- hosts: all
#  become: true
#  become_method: su
#  become_user: secengadmin
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: "yes"
      update_cache: yes
      cache_valid_time: 86400 # 1 day
    become: true
    become_method: su
    become_user: secengadmin
    become_flags: '-s /bin/sh'
